### ISSUE TITLE
Create task for wikistats when new wiki is created

### ISSUE THREAD

**Issue by RhinosF1** [Ladsgroup/Phabricator-maintenance-bot#21]
Per https://phabricator.wikimedia.org/T270547

**Comment by RhinosF1** [comment]
I see https://github.com/Ladsgroup/Phabricator-maintenance-bot/commit/b20ad6cd312984320be04fe74fa58006cc134d05 by @urbanecm but nothing seems to have happened on the ones created Friday unless I'm missing something

**Comment by urbanecm** [comment]
> 
> 
> I see [b20ad6c](https://github.com/Ladsgroup/Phabricator-maintenance-bot/commit/b20ad6cd312984320be04fe74fa58006cc134d05) by @urbanecm but nothing seems to have happened on the ones created Friday unless I'm missing something

You're not, the bot deliberately ignores any tasks with subtasks (even if created by the bot), to avoid duplicates. Maybe I'm missing something, but is there a new wiki task created on Friday (ie. after my commit)?

**Comment by RhinosF1** [comment]
> Maybe I'm missing something, but is there a new wiki task created on Friday (ie. after my commit)?
Looks like all the recent creations were processed prior to this commit so I guess the bot is doing its job and it should work whenever LangCom file the next creation task?

**Comment by Ladsgroup** [comment]
The commit actually has a bug, I fix it.

**Comment by Ladsgroup** [comment]
Oh and it should not be subticket, it should be parent ticket (It's a common mistake: https://phabricator.wikimedia.org/T264962#6527604)

**Comment by Ladsgroup** [comment]
5c3e10ffd04f47c3e6bdc30d55fc8e692471745a fixes it

**Comment by urbanecm** [comment]
Thanks
